version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - shared_data:/app/jobs_files
    env_file:
      - .env
    depends_on:
      - db

  worker:
    build: ./backend
    command: celery -A app.core.celery_app.celery_app worker --loglevel=info
    depends_on:
      - backend
      - redis
      - db
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - shared_data:/app/jobs_files

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  shared_data: